Q1. Create one variable containing following type of data:
(i) string
(ii) list
(iii) float
(iv) tuple

In [ ]:
my_str="hello"
my_list=[1,2,3,"shivvu","shaiksha"]
my_float=3.142
my_tup=(20,78,96,100)

Q2.Given are some following variables containing data:
(i) var1 = ‘ ‘
(ii) var2 = ‘[ DS , ML , Python]’
(iii) var3 = [ ‘DS’ , ’ML’ , ‘Python’ ]
(iv) var4 = 1.

i)str
ii)str
iii)list
iv)float

Q3.Explain the use of the following operators using an example:
(i) /
(ii) %
(iii) //
(iv) **

In [ ]:
print(10/3)
print(10%3)
print(10//3)
print(10**3)

3.3333333333333335
1
3
1000

Q4. Create a list of length 10 of your choice containing multiple types of data. Using for loop print the
element and its data type.

In [ ]:
ele=["hi",23,"hello",99.0,'c',[10,20],"shivvu",46,"nani",23.10]
for i in ele:
     print(i ,":" ,type(i))

hi : <class 'str'>
23 : <class 'int'>
hello : <class 'str'>
99.0 : <class 'float'>
c : <class 'str'>
[10, 20] : <class 'list'>
shivvu : <class 'str'>
46 : <class 'int'>
nani : <class 'str'>
23.1 : <class 'float'>

Q5. Using a while loop, verify if the number A is purely divisible by number B and if so then how many
times it can be divisible.

In [ ]:
a=int(input("enter num1:"))
b=int(input("enter num2:"))
cnt=0
while a%b==0:
    a=a//b
    cnt+=1
if(a==1):
    print("a is divisible by b ,count is:",cnt)
else:
    print("a not divisible by b")

enter num1:8
enter num2:2
a is divisible by b ,count is: 3

Q6. Create a list containing 25 int type data. Using for loop and if-else condition print if the element is
divisible by 3 or not.

In [ ]:
my_list=[3,7,9,8,12,13,15,14,18,23,21,22,24,87,90,33,66,99,55,45,84,21,99,36,99]
for i in my_list:
    if i%3==0:
        print(i,"is divisible by 3")
    else:
        print(i,"not divisble by 3")

3 is divisible by 3
7 not divisble by 3
9 is divisible by 3
8 not divisble by 3
12 is divisible by 3
13 not divisble by 3
15 is divisible by 3
14 not divisble by 3
18 is divisible by 3
23 not divisble by 3
21 is divisible by 3
22 not divisble by 3
24 is divisible by 3
87 is divisible by 3
90 is divisible by 3
33 is divisible by 3
66 is divisible by 3
99 is divisible by 3
55 not divisble by 3
45 is divisible by 3
84 is divisible by 3
21 is divisible by 3
99 is divisible by 3
36 is divisible by 3
99 is divisible by 3

Q7.  mutable and immutable

In [9]:
#mutable=it can be changed
my_list=[10,20,30]
my_list.append(40)

In [11]:
#imuttable:it can't be changed
my_str="shivvu"
my_str+="lakkireddy"